version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - '8000:8000'
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: ['uvicorn', 'main:app', '--host', '0.0.0.0', '--reload']
